### ISSUE TITLE
Plugin not working on webpack 2

### ISSUE THREAD

**Issue by ematipico** [conradz/tap-webpack-plugin#5]
At the moment this plugin doesn't work with webpack 2.
Webpack 2 got rid of the chunk property, this can be seen at this line code

https://github.com/webpack/webpack/blob/v2.1.0-beta.27/lib/Chunk.js#L31

Any chance to have this plugin forked and working for webpack 2?

**Comment by danactive** [comment]
webpack 2.2 has officially been released, so I too am hoping for the breaking version support

**Comment by didiercauvin** [comment]
Hi there,

in the tap-webpack-plugin directory under node_modules, modify line 18 of index.js with the following :

var entry = compilation.chunks.filter(c => c.hasRuntime())

That should do the trick.

Any chance to see this plugin forked and working with webpack 2 any time soon?

**Comment by danactive** [comment]
@conradz Please approve and merge this pull request for webpack2 support on active Node.js versions

**Comment by danactive** [comment]
@conradz Thanks for the quick merge, please bump version and publish to npm

**Comment by conradz** [comment]
`v2.0.0` tagged and published

**Comment by ArtemZag** [comment]
It works with webpack 2 now. But for some reason now it returns exit code 2 (not zero). Even though all tests are passed. (webpack version is 2.2.1)
