### ISSUE TITLE
default without reporter has no output to console

### ISSUE THREAD

**Issue by syarul** [conradz/tap-webpack-plugin#7]
without ```options.reporter``` nothing is being pipe to console

**Comment by conradz** [comment]
This is by design, since this plugin is meant to parse the output and report errors as webpack errors. What is your use case that needs this?

**Comment by syarul** [comment]
Thanks, that's clarify the issue. I thought by default it should parse the standard output without the reporter spec, since I'm looking to pipe the output to something else
